# Python CircleCI 2.0 configuration file
#
version: 2.1
jobs:
  kaggle:
    docker:
      - image: circleci/python:3.8.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install kaggle
      - run:
          name: zip source
          command: |
            zip -r ./data/kaggle/src.zip ./ -x "data/*" "logs/*" "multirun/*" ".git/*" ".ipynb_checkpoints/*" ".vscode/*" "notebook/*"
      - run:
          name: upload to kaggle dataset
          command: |
            kaggle datasets version -p ./data/kaggle/ -m "update" -d
workflows:
  version: 2
  kaggle:
    jobs:
      - kaggle:
          filters:
            branches:
              only: main
