# @package _group_
dataset:
  name: 'WaveformDataset'
  params:
    csv_filename: '${fold.csv_filename}'
    image_column: ''
    group_column: ''
    target_column: ${competition.target_column}
    num_fold: 5
    idx_fold: 0
  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'validation'
    - mode: 'test'
      split: 'test'

transform:
  name: 'base_transform'
  num_preprocessor: 24
