# @package _group_
dataset:
  - name: 'WaveformDatasetWithDist'
    params:
      csv_filename: ${fold.csv_filename}
      image_column: 'filename'
      target_column: ${competition.target_column}
      target_unique_values: ${competition.target_unique_values}
      input_dir: ${input_dir}
      period: 7
      sample_rate: 32000
      num_fold: 5
      idx_fold: -1
      label_smoothing: 0.005
      max_distance: 50
    splits:
      - mode: 'train'
        split: 'train'
  - name: 'WaveformDataset'
    params:
      csv_filename: 'train_soundscape_labels_clip.csv'
      image_column: 'filename'
      target_column: 'birds'
      target_unique_values: ${competition.target_unique_values}
      input_dir: ${input_dir}
      period: 5
      sample_rate: 32000
      images_dir: 'train_soundscapes_clipped'
    splits:
      - mode: 'validation'
        split: 'validation'

transform:
  name: 'base_audio_transform'
  num_preprocessor: 24
