# @package _group_
dataset:
  name: 'WaveformDatasetForWav2Vec'
  params:
    csv_filename: ${fold.csv_filename}
    image_column: 'filename'
    target_column: ${competition.target_column}
    target_unique_values: ${competition.target_unique_values}
    input_dir: ${input_dir}
    period: 5
    sample_rate: 32000
    num_fold: 5
    idx_fold: 0
    label_smoothing: 0.005
    wave2vec_model_name: 'facebook/wav2vec2-base-960h'
  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'validation'
    - mode: 'test'
      split: 'test'

transform:
  name: 'base_audio_transform'
  num_preprocessor: 24
