# @package _group_
dataset:
  name: 'WaveformDataset'
  params:
    csv_filename: ${fold.csv_filename}
    image_column: 'filename'
    target_column: ${competition.target_column}
    target_unique_values: ${competition.target_unique_values}
    secondary_target_column: 'secondary_labels'
    secondary_coef: 0.3
    input_dir: ${input_dir}
    period: 7
    sample_rate: 32000
    num_fold: 5
    idx_fold: 0
    label_smoothing: 0.005
  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'validation'
    - mode: 'test'
      split: 'test'

transform:
  name: 'base_audio_transform'
  num_preprocessor: 24
